In [1]:
import numpy as np


# ============================================================
# 1. BASE DE TREINAMENTO
# ============================================================
# Características:
# [tempo de uso (h), volume de transações (k)]
#
# Classes:
# 0 = Básico
# 1 = Premium

X_treino = np.array([
    [1.0, 1.0],
    [2.0, 2.0],
    [3.0, 2.0],
    [6.0, 5.0],
    [7.0, 6.0],
    [8.0, 7.0]
])

y_treino = np.array([
    0, 0, 0,
    1, 1, 1
])


# ============================================================
# 2. NOVO PONTO A SER CLASSIFICADO
# ============================================================

novo_ponto = np.array([6.5, 5.5])


# ============================================================
# 3. CÁLCULO DAS DISTÂNCIAS EUCLIDIANAS
# ============================================================
# Calcula a distância entre o novo ponto e todas as
# amostras da base de treinamento de uma única vez.
#
# np.linalg.norm calcula a norma/distância euclidiana.
# axis=1 faz o cálculo linha por linha.

distancias = np.linalg.norm(
    X_treino - novo_ponto,
    axis=1
)


# ============================================================
# 4. SELEÇÃO DOS K VIZINHOS MAIS PRÓXIMOS
# ============================================================
# Define a quantidade de vizinhos que serão considerados.

k = 3

# np.argsort() retorna os índices que ordenam as distâncias
# da menor para a maior.
#
# [:k] seleciona apenas os K primeiros índices.

vizinhos_idx = np.argsort(distancias)[:k]


# ============================================================
# 5. VOTAÇÃO DA MAIORIA
# ============================================================
# Obtém as classes dos K vizinhos mais próximos.

votos = y_treino[vizinhos_idx]

# np.bincount() conta quantas vezes cada classe aparece.
# argmax() retorna a classe com maior quantidade de votos.

classe_predita = int(
    np.bincount(votos).argmax()
)


# ============================================================
# 6. RESULTADOS
# ============================================================

print("=" * 50)
print("RESULTADO DA CLASSIFICAÇÃO - KNN")
print("=" * 50)

print(
    f"\nNovo ponto: {novo_ponto}"
)

print(
    f"\nDistâncias para cada amostra:"
    f"\n{np.round(distancias, 2)}"
)

print(
    f"\nÍndices dos {k} vizinhos mais próximos:"
    f"\n{vizinhos_idx}"
)

print(
    f"\nClasses dos vizinhos:"
    f"\n{votos}"
)

print(
    f"\nClasse predita: "
    f"{'Premium (1)' if classe_predita == 1 else 'Básico (0)'}"
)

print("=" * 50)

RESULTADO DA CLASSIFICAÇÃO - KNN

Novo ponto: [6.5 5.5]

Distâncias para cada amostra:
[7.11 5.7  4.95 0.71 0.71 2.12]

Índices dos 3 vizinhos mais próximos:
[3 4 5]

Classes dos vizinhos:
[1 1 1]

Classe predita: Premium (1)
